FWD_SYS_dict:
    VRF_string              : 'EVPN-VRF-'
    VRF_id_start            : 1
    VRF_count               : 2
    VLAN_PER_VRF_count      : 2
    SPINE_COUNT             : 1
    BGP_AS_num              : 200
    OSPF_AS                 : 100

tcam_config_dict:
    Tecate1:
         egr-l3-vlan-qos    : -size 256 -double_wide False
         ing-l2-qos         : -size 256 -double_wide False
    Elysian1:
         egr-l3-vlan-qos    : -size 256 -double_wide False
         ing-l2-qos         : -size 256 -double_wide False


# LEAF-1 data
LEAF_1_dict:
    loop0_ip                : "2.215.1.1"
    SPINE_1_UPLINK_PO:
        po_id               : 215
        spine_loop0_ip      : "11.11.11.11"
        common_rp           : "100.1.1.1"
        leaf_spine_po_v4    : "2.215.1.3"
        leaf_spine_mask_v4  : "/31"
        leaf_spine_po_v6    : "2001:2:215:1::3"
        leaf_spine_mask_v6  : "/64"
        spine_leaf_po_v4    : "2.215.1.2"
        spine_leaf_mask_v4  : "/31"
        spine_leaf_po_v6    : "2001:2:215:1::2"
        spine_leaf_mask_v6  : "/64"
    VPC_data:
        domain_id           : 1
        peer_link_po        : 4096
        VPC_ACC_po          : 1
        kp_al_vrf           : "peer-keep-alive"
        kp_al_ip            : "5.5.5.10"
        backup_svi          : "2000"
        backup_svi_ip       : "1.1.1.2/31"
    NVE_data:
        src_loop            : 'loopback1'
        VTEP_IP             : "2.25.25.25"
        VPC_VTEP_IP         : "2.25.26.25"
        l3_mcast_grp_ip     : '224.1.1.10'
        l2_mcast_grp_ip     : '224.1.1.101'
    VNI_data:
        l3_vlan_start       : 10
        l3_vni_start        : 11000
        l2_vlan_start       : 301
        l2_vni_start        : 20001
        l2_vlan_ipv4_start  : '2.1.1.1'
        l2_vlan_ipv4_mask   : '/24'
        l2_vlan_ipv6_start  : '2001:2:1:1::1'
        l2_vlan_ipv6_mask   : '/64'

# LEAF-2 data
LEAF_2_dict:
    loop0_ip                : "2.216.1.1"
    SPINE_1_UPLINK_PO:
        po_id               : 216
        spine_loop0_ip      : "11.11.11.11"
        common_rp           : "100.1.1.1"
        leaf_spine_po_v4    : "2.216.1.3"
        leaf_spine_mask_v4  : "/31"
        leaf_spine_po_v6    : "2001:2:216:1::3"
        leaf_spine_mask_v6  : "/64"
        spine_leaf_po_v4    : "2.216.1.2"
        spine_leaf_mask_v4  : "/31"
        spine_leaf_po_v6    : "2001:2:216:1::2"
        spine_leaf_mask_v6  : "/64"
    VPC_data:
        domain_id           : 1
        peer_link_po        : 4096
        VPC_ACC_po          : 1
        kp_al_vrf           : "peer-keep-alive"
        kp_al_ip            : "5.5.5.5"
        backup_svi          : "2000"
        backup_svi_ip       : "1.1.1.3/31"
    NVE_data:
        src_loop            : 'loopback1'
        VTEP_IP             : "2.26.26.26"
        VPC_VTEP_IP         : "2.25.26.25"
        l3_mcast_grp_ip     : '224.1.1.10'
        l2_mcast_grp_ip     : '224.1.1.101'
    VNI_data:
        l3_vlan_start       : 10
        l3_vni_start        : 11000
        l2_vlan_start       : 301
        l2_vni_start        : 20001
        l2_vlan_ipv4_start  : '2.1.1.1'
        l2_vlan_ipv4_mask   : '/24'
        l2_vlan_ipv6_start  : '2001:2:1:1::1'
        l2_vlan_ipv6_mask   : '/64'

# LEAF-3 data
LEAF_3_dict:
    loop0_ip                : "2.217.1.1"
    SPINE_1_UPLINK_PO:
        po_id               : 217
        spine_loop0_ip      : "11.11.11.11"
        common_rp           : "100.1.1.1"
        leaf_spine_po_v4    : "2.217.1.3"
        leaf_spine_mask_v4  : "/31"
        leaf_spine_po_v6    : "2001:2:217:1::3"
        leaf_spine_mask_v6  : "/64"
        spine_leaf_po_v4    : "2.217.1.2"
        spine_leaf_mask_v4  : "/31"
        spine_leaf_po_v6    : "2001:2:217:1::2"
        spine_leaf_mask_v6  : "/64"
    NVE_data:
        src_loop            : 'loopback1'
        VTEP_IP             : "2.27.27.27"
        l3_mcast_grp_ip     : '224.1.1.10'
        l2_mcast_grp_ip     : '224.1.1.101'
    VNI_data:
        l3_vlan_start       : 10
        l3_vni_start        : 11000
        l2_vlan_start       : 301
        l2_vni_start        : 20001
        l2_vlan_ipv4_start  : '2.1.1.1'
        l2_vlan_ipv4_mask   : '/24'
        l2_vlan_ipv6_start  : '2001:2:1:1::1'
        l2_vlan_ipv6_mask   : '/64'
    
#Spine-1 data
SPINE_1_dict:
    LEAF_1_UPLINK_PO:
        po_id               : 215
    LEAF_2_UPLINK_PO:
        po_id               : 216
    LEAF_3_UPLINK_PO:
        po_id               : 217
    

# Traffic TGEN Data
LEAF_2_TGEN_data:
    'no_of_ints'            : "2"
    'phy_mode'              : 'fiber'
    'mac'                   : '00:15:06:00:00:01'
    'mac_step'              : '00:00:00:00:00:01'
    'protocol'              : 'ipv46'
    'v4_addr'               : '2.1.1.60'
    'v4_addr_step'          : '0.0.1.0'
    'v4_addr_gateway'       : '2.1.1.1'
    'v4_gateway_step'       : '0.0.1.0'
    'v6_addr'               : '2001:2:1:1::60'
    'v6_addr_step'          : '0:0:0:1::0'
    'v6_gateway'            : '2001:2:1:1::1'
    'v6_gateway_step'       : '0:0:0:1::0'
    'v6_netmask'            : '64'
    'netmask'               : '255.255.255.0'
    'vlan_id'               : '301'
    'vlan_user_priority'    : '3'
    'vlan_id_step'          : '1'
    'frame_size'            : '128'
    'ip_dscp'               : 20
    'ipv6_traffic_class'    : 80
    #'data_tos'              : 40
    'ip_precedence'         : 5
    'enable_data_integrity' : 1
    'L3_dst_addr'           : '2.1.2.70'

# Traffic TGEN Data
LEAF_3_TGEN_data:
    'no_of_ints'            : "2"
    'phy_mode'              : 'fiber'
    'mac'                   : '00:16:01:00:00:01'
    'mac_step'              : '00:00:00:00:00:01'
    'protocol'              : 'ipv46'
    'v4_addr'               : '2.1.1.70'
    'v4_addr_step'          : '0.0.1.0'
    'v4_addr_gateway'       : '2.1.1.1'
    'v4_gateway_step'       : '0.0.1.0'
    'netmask'               : '255.255.255.0'
    'v6_addr'               : '2001:2:1:1::70'
    'v6_addr_step'          : '0:0:0:1::0'
    'v6_gateway'            : '2001:2:1:1::1'
    'v6_gateway_step'       : '0:0:0:1::0'
    'v6_netmask'            : '64'
    'vlan_id'               : '301'
    'vlan_user_priority'    : '3'
    'vlan_id_step'          : '1'
    'frame_size'            : '128'
    'igmp_ver'              : 'v3'
    'mcast_grp_ip'          : '225.1.1.1'
    'mcast_grp_ip_step'     : '0.0.1.0'
    'no_of_grps'            : '10'
    'no_of_mcast_sources'   : '1'
    'ip_dscp'               : 20
    'ipv6_traffic_class'    : 80
    #'data_tos'              : 40
    'ip_precedence'         : 5 
    'enable_data_integrity' : 1
    'L3_dst_addr'           : '2.1.2.60'
