from pyats.easypy import run
from pyats.datastructures.logic import And, Not, Or
import os

def main():

    test_path = os.path.dirname(os.path.abspath(__file__))
    testscript = os.path.join(test_path, './VxLAN_PVMAP_script.py')
    # run api launches a testscript as an individual task.
    run(testscript)
    # to run specific testcase
    #run(testscript,uids =Or('common_setup','setupConfigVxlan','setupPortMappingVxlanConf','setupTgen','VXLAN-PMAP-FUNC-009'))
    #run(testscript,uids =Or('common_setup','setupTgen','VXLAN-PMAP-FUNC-028','VXLAN-PMAP-FUNC-029','VXLAN-PMAP-FUNC-030','VXLAN-PVMAP-OAM-FUNC-031','VXLAN-PVMAP-OAM-FUNC-032','VXLAN-PVMAP-OAM-FUNC-033','VXLAN-PVMAP-OAM-FUNC-034',\
    #                        'VXLAN-PVMAP-OAM-FUNC-035','VXLAN-PVMAP-OAM-FUNC-036','VXLAN-PVMAP-OAM-FUNC-037','VXLAN-PVMAP-OAM-FUNC-038','VXLAN-PVMAP-OAM-FUNC-039','VXLAN-PVMAP-OAM-FUNC-040','VXLAN-PVMAP-OAM-FUNC-041','VXLAN-PVMAP-OAM-FUNC-042',\
    #                        'VXLAN-PVMAP-OAM-FUNC-043','VXLAN-PVMAP-OAM-FUNC-044','VXLAN-PVMAP-OAM-FUNC-045','VXLAN-PVMAP-OAM-FUNC-046','VXLAN-PVMAP-OAM-FUNC-047','VXLAN-PVMAP-OAM-FUNC-048','VXLAN-PVMAP-OAM-FUNC-049','VXLAN-PVMAP-OAM-FUNC-050',\
    #                        'VXLAN-PVMAP-OAM-FUNC-051','VXLAN-PVMAP-OAM-FUNC-052','VXLAN-PVMAP-OAM-FUNC-053','VXLAN-PVMAP-OAM-FUNC-054','VXLAN-PVMAP-OAM-FUNC-055','VXLAN-PVMAP-OAM-FUNC-056','VXLAN-PVMAP-OAM-FUNC-057','VXLAN-PVMAP-OAM-FUNC-058',\
    #                        'VXLAN-PVMAP-OAM-FUNC-059','VXLAN-PVMAP-OAM-FUNC-060','VXLAN-PVMAP-OAM-FUNC-061','VXLAN-PVMAP-OAM-FUNC-062','VXLAN-PVMAP-OAM-FUNC-063','VXLAN-PVMAP-OAM-FUNC-064','VXLAN-PVMAP-OAM-FUNC-065','VXLAN-PVMAP-OAM-FUNC-066',\
    #                        'VXLAN-PVMAP-OAM-FUNC-067','VXLAN-PVMAP-OAM-FUNC-068','VXLAN-PVMAP-OAM-FUNC-069','VXLAN-PVMAP-OAM-FUNC-070','VXLAN-PVMAP-OAM-FUNC-071','VXLAN-PVMAP-OAM-FUNC-072',\
    #                        ))
    # run(testscript,uids =Or('common_setup','setupTgen','VXLAN-PMAP-FUNC-001','VXLAN-PMAP-FUNC-002','VXLAN-PMAP-FUNC-003','VXLAN-PMAP-FUNC-004','VXLAN-PMAP-FUNC-005','VXLAN-PMAP-FUNC-006','VXLAN-PMAP-FUNC-007','VXLAN-PMAP-FUNC-008',\
    #                         'VXLAN-PMAP-FUNC-009','VXLAN-PMAP-FUNC-010','VXLAN-PMAP-FUNC-011','VXLAN-PMAP-FUNC-012','VXLAN-PMAP-FUNC-013','VXLAN-PMAP-FUNC-014','VXLAN-PMAP-FUNC-015','VXLAN-PMAP-FUNC-016','VXLAN-PMAP-FUNC-017',\
    #                         'VXLAN-PMAP-FUNC-018','VXLAN-PMAP-FUNC-019','VXLAN-PMAP-FUNC-020','VXLAN-PMAP-FUNC-021','VXLAN-PMAP-FUNC-022','VXLAN-PMAP-FUNC-023','VXLAN-PMAP-FUNC-024','VXLAN-PMAP-FUNC-025','VXLAN-PMAP-FUNC-026',\
    #                         'VXLAN-PMAP-FUNC-027','VXLAN-PMAP-FUNC-028','VXLAN-PMAP-FUNC-029','VXLAN-PMAP-FUNC-030','VXLAN-PVMAP-OAM-FUNC-031','VXLAN-PVMAP-OAM-FUNC-032','VXLAN-PVMAP-OAM-FUNC-033','VXLAN-PVMAP-OAM-FUNC-034',\
    #                         'VXLAN-PVMAP-OAM-FUNC-035','VXLAN-PVMAP-OAM-FUNC-036','VXLAN-PVMAP-OAM-FUNC-037','VXLAN-PVMAP-OAM-FUNC-038','VXLAN-PVMAP-OAM-FUNC-039','VXLAN-PVMAP-OAM-FUNC-040','VXLAN-PVMAP-OAM-FUNC-041','VXLAN-PVMAP-OAM-FUNC-042',\
    #                         'VXLAN-PVMAP-OAM-FUNC-043','VXLAN-PVMAP-OAM-FUNC-044','VXLAN-PVMAP-OAM-FUNC-045','VXLAN-PVMAP-OAM-FUNC-046','VXLAN-PVMAP-OAM-FUNC-047','VXLAN-PVMAP-OAM-FUNC-048','VXLAN-PVMAP-OAM-FUNC-049','VXLAN-PVMAP-OAM-FUNC-050',\
    #                         'VXLAN-PVMAP-OAM-FUNC-051','VXLAN-PVMAP-OAM-FUNC-052','VXLAN-PVMAP-OAM-FUNC-053','VXLAN-PVMAP-OAM-FUNC-054','VXLAN-PVMAP-OAM-FUNC-055','VXLAN-PVMAP-OAM-FUNC-056','VXLAN-PVMAP-OAM-FUNC-057','VXLAN-PVMAP-OAM-FUNC-058',\
    #                         'VXLAN-PVMAP-OAM-FUNC-059','VXLAN-PVMAP-OAM-FUNC-060','VXLAN-PVMAP-OAM-FUNC-061','VXLAN-PVMAP-OAM-FUNC-062','VXLAN-PVMAP-OAM-FUNC-063','VXLAN-PVMAP-OAM-FUNC-064','VXLAN-PVMAP-OAM-FUNC-065','VXLAN-PVMAP-OAM-FUNC-066',\
    #                         'VXLAN-PVMAP-OAM-FUNC-067','VXLAN-PVMAP-OAM-FUNC-068','VXLAN-PVMAP-OAM-FUNC-069','VXLAN-PVMAP-OAM-FUNC-070','VXLAN-PVMAP-OAM-FUNC-071','VXLAN-PVMAP-OAM-FUNC-072',\
    #                         ))
    #run(testscript,uids =Or('common_setup','setupConfigVxlan','setupPortMappingVxlanConf','setupTgen','VXLAN-PMAP-FUNC-006','VXLAN-PMAP-FUNC-007','VXLAN-PMAP-FUNC-008','VXLAN-PMAP-FUNC-009','VXLAN-PMAP-FUNC-010','VXLAN-PMAP-FUNC-011','VXLAN-PMAP-FUNC-012','VXLAN-PMAP-FUNC-013','VXLAN-PMAP-FUNC-014','VXLAN-PMAP-FUNC-015','VXLAN-PMAP-FUNC-016','VXLAN-PMAP-FUNC-017','VXLAN-PMAP-FUNC-018'))
