FWD_SYS_dict:
    VRF_string                      : 'EVPN-VRF-'
    VRF_id_start                    : 1
    VRF_count                       : 2
    VLAN_PER_VRF_count              : 2
    SPINE_COUNT                     : 1
    BGP_AS_num                      : 200
    OSPF_AS                         : 100

# LEAF-1 data
LEAF_1_dict:
    loop0_ip                        : "2.211.1.1"
    SPINE_1_UPLINK_PO:
        po_id                       : 211
        spine_loop0_ip              : "11.11.11.11"
        common_rp                   : "100.1.1.1"
        leaf_spine_po_v4            : "2.211.1.3"
        leaf_spine_mask_v4          : "/31"
        leaf_spine_po_v6            : "2001:2:211:1::3"
        leaf_spine_mask_v6          : "/64"
        spine_leaf_po_v4            : "2.211.1.2"
        spine_leaf_mask_v4          : "/31"
        spine_leaf_po_v6            : "2001:2:211:1::2"
        spine_leaf_mask_v6          : "/64"
    VPC_data:
        domain_id                   : 100
        peer_link_po                : 100
        VPC_ACC_po                  : 200
        kp_al_vrf                   : "peer-keep-alive"
        kp_al_ip                    : "5.5.5.5"
    NVE_data:
        src_loop                    : 'loopback1'
        VTEP_IP                     : "2.21.21.21"
        VPC_VTEP_IP                 : "2.20.20.20"
        l3_mcast_grp_ip             : '224.1.1.10'
        l2_mcast_grp_ip             : '224.1.1.101'
    VNI_data:
        l3_vlan_start               : 10
        l3_vni_start                : 11001
        l2_vlan_start               : 301
        l2_vni_start                : 20001
        l2_vlan_ipv4_start          : '2.1.1.1'
        l2_vlan_ipv4_mask           : '/24'
        l2_vlan_ipv6_start          : '2001:2:1:1::1'
        l2_vlan_ipv6_mask           : '/64'

# LEAF-2 data
LEAF_2_dict:
    loop0_ip                        : "2.212.1.1"
    SPINE_1_UPLINK_PO:
        po_id                       : 212
        spine_loop0_ip              : "11.11.11.11"
        common_rp                   : "100.1.1.1"
        leaf_spine_po_v4            : "2.212.1.3"
        leaf_spine_mask_v4          : "/31"
        leaf_spine_po_v6            : "2001:2:212:1::3"
        leaf_spine_mask_v6          : "/64"
        spine_leaf_po_v4            : "2.212.1.2"
        spine_leaf_mask_v4          : "/31"
        spine_leaf_po_v6            : "2001:2:212:1::2"
        spine_leaf_mask_v6          : "/64"
    VPC_data:
        domain_id                   : 100
        peer_link_po                : 100
        VPC_ACC_po                  : 200
        kp_al_vrf                   : "peer-keep-alive"
        kp_al_ip                    : "5.5.5.10"
    NVE_data:
        src_loop                    : 'loopback1'
        VTEP_IP                     : "2.22.22.22"
        VPC_VTEP_IP                 : "2.20.20.20"
        l3_mcast_grp_ip             : '224.1.1.10'
        l2_mcast_grp_ip             : '224.1.1.101'
    VNI_data:
        l3_vlan_start               : 10
        l3_vni_start                : 11001
        l2_vlan_start               : 301
        l2_vni_start                : 20001
        l2_vlan_ipv4_start          : '2.1.1.1'
        l2_vlan_ipv4_mask           : '/24'
        l2_vlan_ipv6_start          : '2001:2:1:1::1'
        l2_vlan_ipv6_mask           : '/64'

# LEAF-3 data
LEAF_3_dict:
    loop0_ip                        : "2.213.1.1"
    SPINE_1_UPLINK_PO:
        po_id                       : 213
        spine_loop0_ip              : "11.11.11.11"
        common_rp                   : "100.1.1.1"
        leaf_spine_po_v4            : "2.213.1.3"
        leaf_spine_mask_v4          : "/31"
        leaf_spine_po_v6            : "2001:2:213:1::3"
        leaf_spine_mask_v6          : "/64"
        spine_leaf_po_v4            : "2.213.1.2"
        spine_leaf_mask_v4          : "/31"
        spine_leaf_po_v6            : "2001:2:213:1::2"
        spine_leaf_mask_v6          : "/64"
    NVE_data:
        src_loop                    : 'loopback1'
        VTEP_IP                     : "2.23.23.23"
        l3_mcast_grp_ip             : '224.1.1.10'
        l2_mcast_grp_ip             : '224.1.1.101'
    VNI_data:
        l3_vlan_start               : 10
        l3_vni_start                : 11001
        l2_vlan_start               : 301
        l2_vni_start                : 20001
        l2_vlan_ipv4_start          : '2.1.1.1'
        l2_vlan_ipv4_mask           : '/24'
        l2_vlan_ipv6_start          : '2001:2:1:1::1'
        l2_vlan_ipv6_mask           : '/64'

# Traffic TGEN Data
LEAF_12_TGEN_data:
    'no_of_ints'                    : "1"
    'phy_mode'                      : 'copper'
    'mac'                           : '00:00:20:00:00:01'
    'mac_step'                      : '00:00:00:00:00:01'
    'protocol'                      : 'ipv46'
    'v4_addr'                       : '2.1.1.60'
    'v4_addr_step'                  : '0.0.1.0'
    'v4_gateway'                    : '2.1.1.1'
    'v4_gateway_step'               : '0.0.1.0'
    'v4_netmask'                    : '255.255.255.255'
    'v6_addr'                       : '2001:2:1:1::60'
    'v6_addr_step'                  : '0:0:0:1::0'
    'v6_gateway'                    : '2001:2:1:1::1'
    'v6_gateway_step'               : '0:0:0:1::0'
    'v6_netmask'                    : '128'
    'vlan_id'                       : '301'
    'vlan_id_step'                  : '1'

# Traffic TGEN Data
LEAF_12_SUB_INT_TGEN_data:
    'no_of_ints'                    : "1"
    'phy_mode'                      : 'copper'
    'mac'                           : '00:00:21:00:00:01'
    'mac_step'                      : '00:00:00:00:00:01'
    'protocol'                      : 'ipv46'
    'v4_addr'                       : '3.1.1.60'
    'v4_addr_step'                  : '0.0.1.0'
    'v4_gateway'                    : '3.1.1.1'
    'v4_gateway_step'               : '0.0.1.0'
    'v4_netmask'                    : '255.255.255.255'
    'v6_addr'                       : '2001:3:1:1::60'
    'v6_addr_step'                  : '0:0:0:1::0'
    'v6_gateway'                    : '2001:3:1:1::1'
    'v6_gateway_step'               : '0:0:0:1::0'
    'v6_netmask'                    : '128'
    'vlan_id'                       : '1201'
    'vlan_id_step'                  : '1'

# Traffic TGEN Data
LEAF_3_TGEN_data:
    'no_of_ints'                    : "1"
    'phy_mode'                      : 'copper'
    'mac'                           : '00:00:22:00:00:01'
    'mac_step'                      : '00:00:00:00:00:01'
    'protocol'                      : 'ipv46'
    'v4_addr'                       : '2.1.1.70'
    'v4_addr_step'                  : '0.0.1.0'
    'v4_gateway'                    : '2.1.1.1'
    'v4_gateway_step'               : '0.0.1.0'
    'v4_netmask'                    : '255.255.255.255'
    'v6_addr'                       : '2001:2:1:1::70'
    'v6_addr_step'                  : '0:0:0:1::0'
    'v6_gateway'                    : '2001:2:1:1::1'
    'v6_gateway_step'               : '0:0:0:1::0'
    'v6_netmask'                    : '128'
    'vlan_id'                       : '301'
    'vlan_id_step'                  : '1'
    'igmp_ver'                      : 'v3'
    'mcast_grp_ip'                  : '225.1.1.1'
    'mcast_grp_ip_step'             : '0.0.1.0'
    'no_of_grps'                    : '1'
    'no_of_mcast_sources'           : '1'

# Traffic TGEN Data
LEAF_3_SUB_INT_TGEN_data:
    'no_of_ints'                    : "1"
    'phy_mode'                      : 'copper'
    'mac'                           : '00:00:23:00:00:01'
    'mac_step'                      : '00:00:00:00:00:01'
    'protocol'                      : 'ipv46'
    'v4_addr'                       : '4.1.1.70'
    'v4_addr_step'                  : '0.0.1.0'
    'v4_gateway'                    : '4.1.1.1'
    'v4_gateway_step'               : '0.0.1.0'
    'v4_netmask'                    : '255.255.255.255'
    'v6_addr'                       : '2001:4:1:1::70'
    'v6_addr_step'                  : '0:0:0:1::0'
    'v6_gateway'                    : '2001:4:1:1::1'
    'v6_gateway_step'               : '0:0:0:1::0'
    'v6_netmask'                    : '128'
    'vlan_id'                       : '1301'
    'vlan_id_step'                  : '1'
    'igmp_ver'                      : 'v3'
    'mcast_grp_ip'                  : '225.1.1.1'
    'mcast_grp_ip_step'             : '0.0.1.0'
    'no_of_grps'                    : '1'
    'no_of_mcast_sources'           : '1'
